auto: untarzanice | PLEASE review this commit @Thanatermesis

diff --git a/tree/usr/bin/usb-bootable-elive b/tree/usr/bin/usb-bootable-elive
--- a/tree/usr/bin/usb-bootable-elive
+++ b/tree/usr/bin/usb-bootable-elive
@@ -42,7 +42,7 @@ exit_error(){
     else
         guitool error "$( eval_gettext "Aborted USB writing." )"
     fi
-    guitool info "$( eval_gettext "If there's an issue with the tool we suggest to report it to Elive. You can also try deleting the directory:" ) $cache_dir"
+    guitool info "$( eval_gettext "If there's an issue with the tool, we suggest reporting it to Elive. You can also try deleting the directory:" ) $cache_dir"
 
     rm -f "$TMP_ERROR_LOGS_f" "$TMP_PROGRESS_WORKING_f"
 }
@@ -357,7 +357,7 @@ main(){
     done
 
     if [[ "$UID" != 0 ]] && ! groups | grep -wqs disk ; then
-        $guitool --error --text="$( eval_gettext "This tool needs to be run with admin privileges. Try from a terminal:" ) sudo $(basename $0)"
+        $guitool --error --text="$( eval_gettext "This tool requires admin privileges. Try running it from a terminal:" ) sudo $(basename $0)"
         exit 1
     fi
 
@@ -372,7 +372,7 @@ main(){
 
 
     if ! ((is_auto_mode)) ; then
-        if ! guitool question "$( eval_gettext "This tool will overwrite your USB with an ISO image of Elive or any other operating system. After that, you will be able to boot a computer from this USB with that OS. Remember that Elive also has unique features like a special Persistence to save your data among reboots in a very secure way." )" ; then
+        if ! guitool question "$( eval_gettext "This tool will overwrite your USB with an ISO image of Elive or any other operating system. Afterward, you will be able to boot a computer from this USB with that OS. Remember that Elive also has unique features such as a special Persistence mode to save your data across reboots in a very secure manner." )" ; then
             exit
         fi
     fi
@@ -392,7 +392,7 @@ main(){
                 image_filename_size="$( du -Ls "$image_filename" | awk '{print $1}' )"
                 if ! echo "$image_version" | grep -qs "^[[:digit:]].*[[:digit:]]$" ; then
                     image_version="$( basename "$image_filename" )"
-                    guitool info "$( eval_gettext "This doesn't appear to be a normal Elive version, but we will record it anyway." )"
+                    guitool info "$( eval_gettext "This does not appear to be a normal Elive version, but we will record it anyway." )"
                 fi
             else
                 unset image_filename
@@ -473,7 +473,7 @@ main(){
             # checks
             if [[ -z "$image_url" ]] ; then
                 #guitool error "$( eval_gettext "No versions of Elive for USB available found from the website." )"
-                guitool info "$( eval_gettext "First, download the version of Elive that you want to use. Then insert the downloaded file into this tool in order to write it to your USB memory" )"
+                guitool info "$( eval_gettext "First, download the version of Elive you want to use. Then insert the downloaded file into this tool to write it to your USB memory." )"
                 #el_error "no versions found on the website"
                 exit 0
             fi
@@ -534,10 +534,10 @@ main(){
                 sleep 2
 
                 local message_downloading
-                message_downloading="$( printf "$( eval_gettext "Synchronizing to Elive (%s), please be patient..." )" "$image_version" )"
+                message_downloading="$( printf "$( eval_gettext "Synchronizing to Elive (%s). Please be patient..." )" "$image_version" )"
 
                 local message_comparing
-                message_comparing="$( printf "$( eval_gettext "Searching for particles in the universe to recycle, to save you around 90 percent of the needed download!" )" "" )"
+                message_comparing="$( printf "$( eval_gettext "Searching for particles in the universe to recycle, saving you around 90% of the needed download!" )" "" )"
 
 
                 while kill -0 "$pid" 2>/dev/null
@@ -560,7 +560,7 @@ main(){
 
                 # errors?
                 if grep -qs "No space left" "$TMP_ERROR_LOGS_f" "${TMP_PROGRESS_WORKING_f}" ; then
-                    guitool error "$( eval_gettext "No space left on the device. Please free some space on your disk and then run this tool again." )"
+                    guitool error "$( eval_gettext "No space left on the device. Free some space on your disk and run this tool again." )"
                     rm -f "$image_filename"
                     cd
                     rm -rf "$cache_dir"
@@ -573,7 +573,7 @@ main(){
                     is_checksum_ok=1
                     rm -rf old/
                 else
-                    guitool error "$( eval_gettext "The integrity verification doesn't match. Run this tool again to try with a new download." )"
+                    guitool error "$( eval_gettext "The integrity verification does not match. Run this tool again to try with a new download." )"
                     el_error "md5 verification failed"
                     exit 1
                 fi
@@ -599,7 +599,7 @@ main(){
 
             # errors?
             if grep -qs "No space left" "$TMP_ERROR_LOGS_f" "${TMP_PROGRESS_WORKING_f}" ; then
-                guitool error "$( eval_gettext "No space left on the device. Please free some space on your disk and then run this tool again." )"
+                guitool error "$( eval_gettext "No space left on the device. Free some space on your disk and run this tool again." )"
                 rm -f "$image_filename"
                 cd
                 rm -rf "$cache_dir"
@@ -622,7 +622,7 @@ main(){
                 is_checksum_ok=1
             else
                 rm -f "$image_filename"
-                guitool error "$( eval_gettext "The integrity verification doesn't match. Run this tool again to try with a new download." )"
+                guitool error "$( eval_gettext "The integrity verification does not match. Run this tool again to try with a new download." )"
                 el_error "md5 verification failed"
                 exit 1
             fi
@@ -630,7 +630,7 @@ main(){
         fi
 
         if ! ((is_checksum_ok)) ; then
-            guitool error "$( eval_gettext "The integrity verification doesn't look to be correct." )"
+            guitool error "$( eval_gettext "The integrity verification does not appear to be correct." )"
             el_error "integrity has not been verified"
             exit 1
         fi
@@ -643,7 +643,7 @@ main(){
 
     # not inserted ? do it!
     if [[ "${#menu[@]}" -lt 3 ]] ; then
-        guitool info "$( eval_gettext "Please insert your USB media to record before continuing." )"
+        guitool info "$( eval_gettext "Insert your USB media to record before continuing." )"
 
         generate_menu_selector
         if [[ "${#menu[@]}" -lt 3 ]] ; then
@@ -653,12 +653,12 @@ main(){
     fi
 
     if [[ "${#menu[@]}" -lt 3 ]] ; then
-        #guitool error "$( eval_gettext "No USB thumb drives were found." )"
-        if guitool question "$( eval_gettext "No USB thumb drives found. Do you want to show all the available hard disks? (Use this option with caution, you can destroy all your computer's data if you select the wrong disk!)" )" ; then
+        #guitool error "$( eval_gettext "No USB thumb drives found." )"
+        if guitool question "$( eval_gettext "No USB thumb drives found. Do you want to show all available hard disks? (Use caution, selecting the wrong disk can destroy all your computer's data!)" )" ; then
 
             generate_menu_selector "include_hd"
             if [[ "${#menu[@]}" -lt 3 ]] ; then
-                guitool error "$( eval_gettext "No USB thumb drives were found." )"
+                guitool error "$( eval_gettext "No USB thumb drives found." )"
                 exit 1
             fi
 
@@ -688,13 +688,13 @@ main(){
     fi
 
     local message_select_usb
-    message_select_usb="$( printf "$( eval_gettext "Select the USB device where to record the system. All the data and partitions inside it will be permanently deleted!" )" "" )"
+    message_select_usb="$( printf "$( eval_gettext "Select the USB device to record the system. All data and partitions inside it will be permanently deleted!" )" "" )"
 
     if ! [[ -n "$image_device" ]] || ! [[ -b "$image_device" ]] ; then
         image_device="$( $guitool --list --height=300 --width=600 --text="$message_select_usb" --column="$( eval_gettext "Device" )" --column="$( eval_gettext "Size" )" --column="$( eval_gettext "Details" )" "${menu[@]}" || echo cancel )"
 
         if [[ "$image_device" = "cancel" ]] || [[ -z "$image_device" ]] || [[ ! -b "$image_device" ]] ; then
-            if guitool question "$( eval_gettext "You have not selected any device to use. Do you want to exit?" )" ; then
+            if guitool question "$( eval_gettext "You have not selected a device to use. Do you want to exit?" )" ; then
                 exit 1
             else
                 generate_menu_selector
@@ -716,7 +716,7 @@ main(){
         #if udevadm info --query=property --name="$image_device" | grep -qs "ID_TYPE=disk" ; then
             el_debug "disabling dd in sync mode (progress bar will be not very precise)"
             local message_doing_magic_extra
-            message_magic_extra="$( printf "$( eval_gettext "Note: due to optimizations, the progress bar will appear slower in the end." )" "" )"
+            message_magic_extra="$( printf "$( eval_gettext "Note: Due to optimizations, the progress bar will appear slower towards the end." )" "" )"
 
             unset opts_dd_sync
         #fi
@@ -732,16 +732,16 @@ main(){
     # record Elive to device {{{
     if [[ -s "$image_filename" ]] && [[ -b "$image_device" ]] ; then
         local message_recording
-        message_recording="$( printf "$( eval_gettext "Recording Elive %s onto your %s device" )" "$image_version" "$image_device" )"
+        message_recording="$( printf "$( eval_gettext "Recording Elive %s onto your %s device." )" "$image_version" "$image_device" )"
         if ! echo "$image_version" | grep -qs "^[[:digit:]].*[[:digit:]]$" ; then
-            message_recording="$( printf "$( eval_gettext "Recording %s onto your %s device" )" "${image_version}" "$image_device" )"
+            message_recording="$( printf "$( eval_gettext "Recording %s onto your %s device." )" "${image_version}" "$image_device" )"
         fi
 
         # check if size is enough
         if [[ -n "$image_device_size" ]] && [[ -n "$image_filename_size" ]] && [[ "${image_device_size}" -lt "${image_filename_size}000" ]] ; then
             #el_warning "temporal report: USB is smaller than image to record: image is '${image_filename_size}' and device is '${image_device_size}'. "
 
-            if ! guitool question "$( eval_gettext "The detected size of your USB media appears to be smaller than the size of the image you want to record to it. This may result in a corrupted system. Do you want to continue anyway?" )" ; then
+            if ! guitool question "$( eval_gettext "The detected size of your USB media is smaller than the size of the image you want to record. This may result in a corrupted system. Do you want to continue anyway?" )" ; then
                 exit
             fi
         fi
@@ -762,11 +762,11 @@ main(){
 
         if ((is_persistence_included)) ; then
             if ((is_auto_mode)) ; then
-                if ! guitool question "$( eval_gettext "You have a persistence partition in your USB, proceeding will delete it. Are you sure to continue?" )" ; then
+                if ! guitool question "$( eval_gettext "You have a persistence partition on your USB. Proceeding will delete it. Are you sure you want to continue?" )" ; then
                     exit 1
                 fi
             else
-                if ! guitool question "$( eval_gettext "You seem to have a Persistence partition included on this USB, if you continue you will lose all the data on it, like possible users and files. Continue anyway?" )" ; then
+                if ! guitool question "$( eval_gettext "You seem to have a Persistence partition on this USB. If you continue, you will lose all the data on it, including possible users and files. Do you want to continue anyway?" )" ; then
                     exit
                 fi
             fi
@@ -816,7 +816,7 @@ main(){
         #if zcat "$image_filename" | pv -i 2 -L 600M -n -W -s "${image_filename_size}k" 2>"${TMP_PROGRESS_WORKING_f}" | dd of="/dev/null" bs=8M ; then
 
         # confirm write
-        if ((is_hd_included)) && ! guitool question "$( eval_gettext "You selected to write to a hard disk instead of a USB thumb drive. YOU MAY LOSE DATA if you selected the wrong one. Do you want to continue? This disk is going to be erased entirely! :" ) ${image_device}" ; then
+        if ((is_hd_included)) && ! guitool question "$( eval_gettext "You selected to write to a hard disk instead of a USB thumb drive. YOU MAY LOSE DATA if you selected the wrong device. Do you want to continue? This disk will be erased entirely!:" ) ${image_device}" ; then
             exit 1
         fi
 
@@ -830,7 +830,7 @@ main(){
         else
             # full write zeroes
             if ((is_full_rewrite)) ; then
-                guitool working_start "$( eval_gettext "Please be patient, writing an entire USB with zeros is a very slow task. This operation will repair or improve your USB media making it work more reliably." )"
+                guitool working_start "$( eval_gettext "Please be patient. Writing an entire USB with zeros is a slow task. This operation will repair or improve your USB media, making it more reliable." )"
                 dd if=/dev/zero of="$image_device" bs=8M  2>"$TMP_ERROR_LOGS_f"
                 sync
                 guitool working_stop
@@ -862,7 +862,7 @@ main(){
         # show possible errors found
         if ((is_record_failed)) ; then
             el_error "dd was unable to write. Image size '${image_filename_size}', Image file '${image_filename}', Device '${image_device}', Device size '${image_device_size}' \nlogs: $(cat "$TMP_ERROR_LOGS_f" )\n$(dmesg | grep -i error | tail -4)\Partitions:\n$( EL_DEBUG=0 partitions-list --show-all --show-disks --show-raw )"
-            guitool error "$( eval_gettext "Error writing to the USB" ). $( eval_gettext "Failed to copy all the content, is your USB too small for the ISO? This error can be also caused by a bad quality USB. We recommend only using good quality devices, for example, the SanDisk Ultra Flair 32GB, which is cheap and fast enough to have the Persistence feature work well. You could also try running this tool from a terminal with the option to perform a forced full cleansing of your device, like:" )  $(basename "$0" ) --clean"
+            guitool error "$( eval_gettext "Error writing to the USB" ). $( eval_gettext "Failed to copy all the content, is your USB too small for the ISO? This error can also be caused by a bad quality USB. We recommend only using good quality devices, such as the SanDisk Ultra Flair 32GB, which is cheap and fast enough to ensure the Persistence feature works well. You could also try running this tool from a terminal with the option to perform a forced full cleansing of your device, like:" )  $(basename "$0" ) --clean"
             exit 1
         fi
     fi
